### ISSUE TITLE
Row selection not matching activation status

### ISSUE THREAD

**Issue by tsmbland** [ImperialCollegeLondon/paricia#250] opened 2024-04-04 10:04 UTC
The main callback in the validation app is designed to automatically select entries for which `is_active` is `True`, whenever data is loaded. However this doesn't seem to be working properly. I'm not sure what's going wrong.

**Comment by dalonsoa** [comment] 2024-10-08 14:56
@tsmbland , I cannot reproduce the error. If I manually validate a couple of entries in the Admin, marking one as active and the other one as inactive:

![Image](https://github.com/user-attachments/assets/3ecc354d-f84d-4b69-abcd-9af23c945cfc)

the checkbox appears correct checked/unchecked based on that activation status when going to the validation screen:

![Image](https://github.com/user-attachments/assets/e8641f3d-1e99-47dc-835a-871a20947416)

Maybe it was fixed automatically in the meantime?

**Comment by dalonsoa** [comment] 2024-10-08 14:58
Obviously, they only appear when requesting validated data. When requesting not validated data, only active entries appear since they can only be set as not active if they are also validated. See https://github.com/ImperialCollegeLondon/paricia/blob/cefd92384a26767c68204e02e3ad0b1456b84664/measurement/models.py#L254

**Comment by dalonsoa** [comment] 2024-10-17 08:22
Closing, for now as it does not seem to be an issue anymore.

**Closed by dalonsoa** 2024-10-17 08:22 UTC
Labels: bug, frontend
